name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for HTML validation)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install HTML validator
        run: npm install -g html-validator

      - name: Validate HTML
        run: html-validator --file index.html

      - name: Deploy to GitHub Pages (if on main branch)
        if: github.ref == 'refs/heads/main'  # Only deploy on push to main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Deploy everything in the root